//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMSEntities : DbContext
    {
        public IMSEntities()
            : base("name=IMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TIMS_Contractor> TIMS_Contractor { get; set; }
        public virtual DbSet<TIMS_Discipline> TIMS_Discipline { get; set; }
        public virtual DbSet<TIMS_Phase> TIMS_Phase { get; set; }
        public virtual DbSet<TIMS_Project> TIMS_Project { get; set; }
        public virtual DbSet<TIMS_ProjectActionItem> TIMS_ProjectActionItem { get; set; }
        public virtual DbSet<TIMS_ProjectActionItemWorkflow> TIMS_ProjectActionItemWorkflow { get; set; }
        public virtual DbSet<TIMS_ProjectArea> TIMS_ProjectArea { get; set; }
        public virtual DbSet<TIMS_ProjectAttachment> TIMS_ProjectAttachment { get; set; }
        public virtual DbSet<TIMS_ProjectComment> TIMS_ProjectComment { get; set; }
        public virtual DbSet<TIMS_ProjectContractor> TIMS_ProjectContractor { get; set; }
        public virtual DbSet<TIMS_ProjectDiscipline> TIMS_ProjectDiscipline { get; set; }
        public virtual DbSet<TIMS_ProjectDisciplineInterfaceType> TIMS_ProjectDisciplineInterfaceType { get; set; }
        public virtual DbSet<TIMS_ProjectDisciplineInterfaceTypeField> TIMS_ProjectDisciplineInterfaceTypeField { get; set; }
        public virtual DbSet<TIMS_ProjectInterfaceAgreement> TIMS_ProjectInterfaceAgreement { get; set; }
        public virtual DbSet<TIMS_ProjectInterfaceAgreementWorkflow> TIMS_ProjectInterfaceAgreementWorkflow { get; set; }
        public virtual DbSet<TIMS_ProjectInterfacePoint> TIMS_ProjectInterfacePoint { get; set; }
        public virtual DbSet<TIMS_ProjectInterfacePointFieldEntry> TIMS_ProjectInterfacePointFieldEntry { get; set; }
        public virtual DbSet<TIMS_ProjectInterfacePointWorkflow> TIMS_ProjectInterfacePointWorkflow { get; set; }
        public virtual DbSet<TIMS_ProjectPackage> TIMS_ProjectPackage { get; set; }
        public virtual DbSet<TIMS_ProjectPhysicalArea> TIMS_ProjectPhysicalArea { get; set; }
        public virtual DbSet<TIMS_Role> TIMS_Role { get; set; }
        public virtual DbSet<TIMS_User> TIMS_User { get; set; }
        public virtual DbSet<TIMS_UserRole> TIMS_UserRole { get; set; }
        public virtual DbSet<TIMS_UserWatchlistItem> TIMS_UserWatchlistItem { get; set; }
        public virtual DbSet<TIMS_WorkflowAction> TIMS_WorkflowAction { get; set; }
        public virtual DbSet<TIMS_WorkflowState> TIMS_WorkflowState { get; set; }
        public virtual DbSet<TIMS_WorkflowType> TIMS_WorkflowType { get; set; }
    }
}
