//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CommentVote
    {
        public System.Guid ID { get; set; }
        public int Vote { get; set; }
        public string IP { get; set; }
        public System.Guid CommentID { get; set; }
    
        public virtual T_Comment T_Comment { get; set; }
    }
}
