//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Comment()
        {
            this.T_Comment1 = new HashSet<T_Comment>();
            this.T_CommentVote = new HashSet<T_CommentVote>();
        }
    
        public System.Guid ID { get; set; }
        public string DomainID { get; set; }
        public string Path { get; set; }
        public string IP { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string QueryString { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Comment> T_Comment1 { get; set; }
        public virtual T_Comment T_Comment2 { get; set; }
        public virtual T_Domain T_Domain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CommentVote> T_CommentVote { get; set; }
    }
}
