//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMS_ProjectDisciplineInterfaceTypeField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIMS_ProjectDisciplineInterfaceTypeField()
        {
            this.TIMS_ProjectInterfacePointFieldEntry = new HashSet<TIMS_ProjectInterfacePointFieldEntry>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> InterfaceTypeID { get; set; }
    
        public virtual TIMS_ProjectDisciplineInterfaceType TIMS_ProjectDisciplineInterfaceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectInterfacePointFieldEntry> TIMS_ProjectInterfacePointFieldEntry { get; set; }
    }
}
