//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMS_ProjectInterfacePoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIMS_ProjectInterfacePoint()
        {
            this.TIMS_ProjectInterfaceAgreement = new HashSet<TIMS_ProjectInterfaceAgreement>();
            this.TIMS_UserWatchlistItem = new HashSet<TIMS_UserWatchlistItem>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProjectID { get; set; }
        public Nullable<System.Guid> LeadPackageID { get; set; }
        public Nullable<System.Guid> InterfacePackageID { get; set; }
        public Nullable<System.Guid> SupportPackageID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> FinalizeDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
    
        public virtual TIMS_Project TIMS_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectInterfaceAgreement> TIMS_ProjectInterfaceAgreement { get; set; }
        public virtual TIMS_ProjectPackage TIMS_ProjectPackage { get; set; }
        public virtual TIMS_ProjectPackage TIMS_ProjectPackage1 { get; set; }
        public virtual TIMS_ProjectPackage TIMS_ProjectPackage2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_UserWatchlistItem> TIMS_UserWatchlistItem { get; set; }
    }
}
