//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMS_Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIMS_Project()
        {
            this.TIMS_ProjectActionItem = new HashSet<TIMS_ProjectActionItem>();
            this.TIMS_ProjectArea = new HashSet<TIMS_ProjectArea>();
            this.TIMS_ProjectContractor = new HashSet<TIMS_ProjectContractor>();
            this.TIMS_ProjectDiscipline = new HashSet<TIMS_ProjectDiscipline>();
            this.TIMS_ProjectInterfacePoint = new HashSet<TIMS_ProjectInterfacePoint>();
            this.TIMS_ProjectPackage = new HashSet<TIMS_ProjectPackage>();
            this.TIMS_ProjectPhysicalArea = new HashSet<TIMS_ProjectPhysicalArea>();
            this.TIMS_UserRole = new HashSet<TIMS_UserRole>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectActionItem> TIMS_ProjectActionItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectArea> TIMS_ProjectArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectContractor> TIMS_ProjectContractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectDiscipline> TIMS_ProjectDiscipline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectInterfacePoint> TIMS_ProjectInterfacePoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectPackage> TIMS_ProjectPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectPhysicalArea> TIMS_ProjectPhysicalArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_UserRole> TIMS_UserRole { get; set; }
    }
}
