//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMS_ProjectInterfaceAgreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIMS_ProjectInterfaceAgreement()
        {
            this.TIMS_ProjectActionItem = new HashSet<TIMS_ProjectActionItem>();
            this.TIMS_ProjectInterfaceAgreementWorkflow = new HashSet<TIMS_ProjectInterfaceAgreementWorkflow>();
            this.TIMS_UserWatchlistItem = new HashSet<TIMS_UserWatchlistItem>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> InterfacePointID { get; set; }
        public Nullable<System.Guid> RequestorPackageID { get; set; }
        public Nullable<System.Guid> ResponderPackageID { get; set; }
        public Nullable<System.Guid> RequestorUserID { get; set; }
        public Nullable<System.Guid> RequestorTechnicalContactID { get; set; }
        public Nullable<System.Guid> ResponderInterfaceManagerID { get; set; }
        public Nullable<System.Guid> ResponderTechnicalContactID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> NeedDate { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectActionItem> TIMS_ProjectActionItem { get; set; }
        public virtual TIMS_ProjectInterfacePoint TIMS_ProjectInterfacePoint { get; set; }
        public virtual TIMS_ProjectPackage TIMS_ProjectPackage { get; set; }
        public virtual TIMS_ProjectPackage TIMS_ProjectPackage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectInterfaceAgreementWorkflow> TIMS_ProjectInterfaceAgreementWorkflow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_UserWatchlistItem> TIMS_UserWatchlistItem { get; set; }
    }
}
