//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMS_ProjectComment
    {
        public System.Guid ID { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> ProjectInterfacePointWorkflowID { get; set; }
        public Nullable<System.Guid> ProjectInterfaceAgreementWorkflowID { get; set; }
        public Nullable<System.Guid> ProjectActionItemWorkflowID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual TIMS_ProjectActionItemWorkflow TIMS_ProjectActionItemWorkflow { get; set; }
        public virtual TIMS_ProjectInterfaceAgreementWorkflow TIMS_ProjectInterfaceAgreementWorkflow { get; set; }
        public virtual TIMS_ProjectInterfacePointWorkflow TIMS_ProjectInterfacePointWorkflow { get; set; }
        public virtual TIMS_User TIMS_User { get; set; }
    }
}
