//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMS_ProjectPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIMS_ProjectPackage()
        {
            this.TIMS_ProjectAttachment = new HashSet<TIMS_ProjectAttachment>();
            this.TIMS_ProjectInterfaceAgreement = new HashSet<TIMS_ProjectInterfaceAgreement>();
            this.TIMS_ProjectInterfaceAgreement1 = new HashSet<TIMS_ProjectInterfaceAgreement>();
            this.TIMS_ProjectInterfacePoint = new HashSet<TIMS_ProjectInterfacePoint>();
            this.TIMS_ProjectInterfacePoint1 = new HashSet<TIMS_ProjectInterfacePoint>();
            this.TIMS_ProjectInterfacePoint2 = new HashSet<TIMS_ProjectInterfacePoint>();
            this.TIMS_UserRole = new HashSet<TIMS_UserRole>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ProjectID { get; set; }
        public Nullable<System.Guid> ProjectContractorID { get; set; }
    
        public virtual TIMS_Project TIMS_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectAttachment> TIMS_ProjectAttachment { get; set; }
        public virtual TIMS_ProjectContractor TIMS_ProjectContractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectInterfaceAgreement> TIMS_ProjectInterfaceAgreement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectInterfaceAgreement> TIMS_ProjectInterfaceAgreement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectInterfacePoint> TIMS_ProjectInterfacePoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectInterfacePoint> TIMS_ProjectInterfacePoint1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_ProjectInterfacePoint> TIMS_ProjectInterfacePoint2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMS_UserRole> TIMS_UserRole { get; set; }
    }
}
